INSERT INTO book_category (book_id, category_id) VALUES
(1, 1), (1, 2),  -- 1984 (Roman, Science-Fiction)
(2, 2),          -- Dune (Science-Fiction)
(3, 3),          -- Le Seigneur des Anneaux (Fantaisie)
(4, 3),          -- Harry Potter (Fantaisie)
(5, 1), (5, 6),  -- L'Étranger (Roman, Philosophie)
(6, 1),          -- Le Petit Prince (Roman)
(7, 2),          -- Fondation (Science-Fiction)
(8, 1), (8, 5),  -- Les Misérables (Roman, Histoire)
(9, 1), (9, 6),  -- La Peste (Roman, Philosophie)
(10, 5),         -- Guerre et Paix (Histoire)
(11, 1), (11, 6),-- Crime et Châtiment (Roman, Philosophie)
(12, 1), (12, 6),-- Les Fleurs du Mal (Roman, Philosophie)
(13, 7),         -- Cosmos (Science)
(14, 7),         -- Une brève histoire du temps (Science)
(15, 5), (15, 6);-- L'Art de la guerre (Histoire, Philosophie)
